capstone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('note.urls')),
]

note/urls.py
from os import name
from django.urls import path

from . import views

app_name = "note"
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),

    # api endpoints
    path('note', views.note, name="note"),
    path('note/edit', views.note_edit, name="note_edit"),
    path('note/edit/archive', views.note_archive, name="note_archive"),
    path('labels', views.labels, name="labels"),
]

note/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):
    """
        Represents a user with:
        username, email, password
    """
    email = models.EmailField(blank=False)
    
    def __str__(self):
        return f"{self.username}"

    
class Note(models.Model):
    """Represent a note"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notes")
    text = models.TextField(blank=False)
    color = models.CharField(max_length=64, blank=True)
    labels = models.ManyToManyField("Label", blank=True, related_name="notes")
    is_archived = models.BooleanField(default=False)
    # datetime when post last updated or post for the first time
    datetime = models.DateTimeField(auto_now_add = True)

    def save(self, *args, **kwargs):
        allowed_colors = ('red', 'green', 'blue', 'purple', 'white', '')

        if self.color not in allowed_colors:
            return
        
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        for label in self.labels.all():
            if label.notes.count() == 1:
                label.delete()
        
        super().delete(*args, **kwargs)
            

    def __str__(self):
        return f"Note {self.id} : {self.text[ : 20]}"

    def serializer(self):
        return {
            'noteId': self.id,
            'username': self.user.username,
            'text': self.text,
            'color': self.color,
            'labels': [label.serializer() for label in self.labels.all()],
            'isArchived': self.is_archived,
            'datetime': self.datetime.strftime("%b %d %Y, %I:%M %p"),
        }

class Label(models.Model):
    """Represent labels"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="labels")
    label = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f"Label {self.id} : {self.label}"

    def serializer(self):
        return {
            'labelId': self.id,
            'username': self.user.username,
            'label': self.label,
        }

note/forms.py
from django import forms

from .models import User

class RegisterForm(forms.ModelForm):
    password_confirmation = forms.CharField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean_password_confirmation(self):
        confirmed_password = self.cleaned_data['password_confirmation']
        if confirmed_password != self.cleaned_data['password']:
            raise forms.ValidationError("Passwords should match")
        
        return confirmed_password

note/views.py
import json
from os import stat
from markdown2 import markdown
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from .models import Label, Note, User
from .forms import *

# Create your views here.

@login_required(redirect_field_name="" ,login_url=reverse_lazy('note:login'))
def index(request):
    return render(request, 'note/index.html')

@login_required(redirect_field_name="", login_url=reverse_lazy('note:login'))
def note(request):
    """
        POST: Save a note to database
        GET: Responce with the category's note's summary from database
    """
    if request.method == "POST":
        # Get data from the post request
        note_data = json.loads(request.body)

        # clean the data
        note_data['text'] = note_data['text'].strip()
        note_data['color'] = note_data['color'].lower()
        note_data['labels'] = tuple(label.strip() for label in note_data['labels'])

        # check validity of data
        if note_data['text'] == '':
            return JsonResponse({'error': 'Text field cannot be empty'}, status=400)

        # create the note
        new_note = Note.objects.create(
            user = request.user,
            text = note_data['text'],
            color = note_data['color']
        )        

        if note_data['labels']:
            for label in note_data['labels']:
                new_label, _ = Label.objects.get_or_create(user=request.user, label=label)
                new_note.labels.add(new_label)
                
        new_note.save()

        # Return the note created
        note_created = new_note.serializer()
        note_created['text'] = markdown(note_created['text'], safe_mode="escape")[:300] # First 300 characters

        # because markdown2 does not put <br> when / encounter like markdown
        note_created['text'] = note_created['text'].replace('\\', '<br>')

        return JsonResponse(note_created, status=201)
    if request.method == "GET":
        category = request.GET.get('category')

        if category == 'all':  # all unarchived
            notes = Note.objects.filter(user=request.user, is_archived=False)
        elif category == 'archived':
            notes = Note.objects.filter(user=request.user, is_archived=True)
        else:
            try:
                label = Label.objects.get(user=request.user, label=category)
                notes = Note.objects.filter(user=request.user, labels=label)
            except Label.DoesNotExist:
                return JsonResponse({'error':'Invalid view option'}, status=400)

        notes = notes.order_by("-datetime").all()
        notes_serialized = []
        for note in notes:
            note = note.serializer()
            note['text'] = markdown(note['text'], safe_mode="escape")[:300]
            # because markdown2 does not put <br> when / encounter like markdown
            note['text'] = note['text'].replace('\\', '<br>')
            notes_serialized.append(note)

        return JsonResponse(notes_serialized, safe=False, status=200)

@login_required(redirect_field_name="", login_url=reverse_lazy('note:login'))
def note_edit(request):
    """For Viewing and editing a note
    GET: Returns a single note with the given id, error if id is not valid
    PUT: Edit the note
    DELETE: Deletes a note
    """
    if request.method == 'GET':
        note_id = request.GET['noteId']

        try:
            note = Note.objects.get(id=note_id)
        except Note.DoesNotExist:
            return JsonResponse({'error': 'note does not exist'}, status=400)

        note = note.serializer()
        note['markdown'] = note['text']
        note['text'] = markdown(note['text'], safe_mode="escape")
        # because markdown2 does not put <br> when / encounter like markdown
        note['text'] = note['text'].replace('\\', '<br>')

        return JsonResponse(note, status=200)
    elif request.method == "PUT":
        # Get data from the post request
        note_data = json.loads(request.body)

        # clean the data
        note_data['text'] = note_data['text'].strip()
        note_data['color'] = note_data['color'].lower()
        note_data['labels'] = tuple(label.strip() for label in note_data['labels'])
        note_data['noteId'] = int(note_data['noteId'])

        # check validity of data
        if note_data['text'] == '':
            return JsonResponse({'error': 'Text field cannot be empty'}, status=400)

        # get the note
        try:
            note = Note.objects.get(id=note_data['noteId'])
        except Note.DoesNotExist:
            return JsonResponse({'error': 'note id is invalid'}, status=400)
        
        # edit note's content
        note.text = note_data['text']
        note.color = note_data['color']

        # delete old labels
        note.labels.clear()
        # add new labels
        if note_data['labels']:
            for label in note_data['labels']:
                new_label, _ = Label.objects.get_or_create(user=request.user, label=label)
                note.labels.add(new_label)
                
        note.save()

        # Return the note edited note
        edited_note = note.serializer()
        edited_note['text'] = markdown(edited_note['text'], safe_mode="escape")[:300] # First 300 characters
        # because markdown2 does not put <br> when / encounter like markdown
        edited_note['text'] = edited_note['text'].replace('\\', '<br>')

        return JsonResponse(edited_note, status=201)
    elif request.method == "DELETE":
        """Deletes a note from database"""
        note_id = int(json.loads(request.body)['noteId'])

        # get the note
        try:
            note = Note.objects.get(id=note_id)
        except Note.DoesNotExist:
            return JsonResponse({'error': 'note id is not valid'}, status=400)
        
        # delete the note
        note.delete()

        return JsonResponse({'message': 'deleted the note'}, status=200)

def note_archive(request):
    """Archive/Unarchive a note"""
    if request.method == "PUT":
        note_id = int(json.loads(request.body)['noteId'])
        
        # get the note
        try:
            note = Note.objects.get(id=note_id)
        except Note.DoesNotExist:
            return JsonResponse({'error': 'note id is not valid'}, status=400)
        
        # Toggle the archive state
        note.is_archived = not note.is_archived
        note.save()

        return JsonResponse({'message': 'Toggled the archive'}, status=200)

def labels(request):
    """Return all labels"""
    if request.method == "GET":
        labels = Label.objects.filter(user=request.user)

        labels = [label.serializer() for label in labels]

        labels.sort(key=lambda label: label['label'])

        return JsonResponse(labels, safe=False, status=200)

def login_view(request):
    """
        Get: display login form
        Post: login user into a session
    """
    if request.method == "POST":
        # Get details from form
        username = request.POST["username"]
        password = request.POST['password']

        # attempt to sign in
        user = authenticate(request, username=username, password=password)

        # check if authetication is successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('note:index'))
        else:
            return render(request, 'note/login.html', {
                'message': 'Invalid username and/or password',
            }, status=401)
    if request.method == "GET":
        # if already logged in then goto index
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('note:index'))
        return render(request, 'note/login.html', status=200)


def logout_view(request):
    """Logout user from current session"""

    logout(request)
    return HttpResponseRedirect(reverse('note:login'))


def register(request):
    """
        Get: Display register page
        Post: Register a new user
    """
    if request.method == "POST":
        new_user_details = RegisterForm(request.POST)

        # check for empty fields, unique username, and password match
        if not new_user_details.is_valid():
            return render(request, 'note/register.html', {
                'register_form': new_user_details,
            }, status=400)
    
        # create new user
        new_user = User.objects.create_user(
            new_user_details.cleaned_data['username'],
            new_user_details.cleaned_data['email'],
            new_user_details.cleaned_data['password']
        )
        # save new user to database
        new_user.save()
        
        # login new user
        login(request, new_user)

        return HttpResponseRedirect(reverse('note:index'), status=201)
    elif request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('note:index'))
        return render(request, 'note/register.html', status=200)

note/templates/note/index.html
{% extends 'note/layout.html' %}

{% block main %}
    <div id="note-box" class="rounded mt-4">
        <div contenteditable="true" id="note-text" aria-multiline="true" role="textbox" aria-label="take a note...">
        </div>
        <div class="invalid-feedback alert alert-danger text-center py-2 my-1">Please enter some text</div>
        <div class="controls p-2 row mx-0 w-100">
            <input type="text" class="form-control col-sm-12 col-md-8" id="tags" placeholder="Comma separated labels">
            <div class="div row mx-0 col-md-4 px-0">
                <select name="color" id="color" class="custom-select col-6">
                    <option>White</option>
                    <option>Red</option>
                    <option>Green</option>
                    <option>Blue</option>
                    <option>Purple</option>
                </select>
                <button class="save-btn btn btn-light btn-outline-dark border font-weight-bold px-4 py-1 col-6" id="create-note" type="submit">Save</button>
            </div>
        </div>
    </div>

    <div id="labels" class="container text-center">
        <h1 class="display-4 mb-4">Labels</h1>
        <div class="message alert alert-info mt-5 text-center"></div>
        <div class="row pt-5" id="label-btns" style="min-height: 100vh;">
        </div>
    </div>

    <div id="message" class="alert alert-info mt-5 text-center"></div>

    <div id="notes" class="card-columns mt-5">
    </div>

    <div id="edit-note-box" class="rounded mt-4">
        <div id="edit-menu" class="d-flex justify-content-end">
            <button id="edit" class="btn btn-secondary rounded-0">Edit</button>
            <button id="archive" class="btn btn-warning rounded-0">Archive/Unarchive</button>
            <button id="delete" class="btn btn-danger rounded-0">Delete</button>
        </div>
        <div contenteditable="false" id="edit-note-text" aria-multiline="true" role="textbox" aria-label="take a note...">
        </div>
        <div class="invalid-feedback alert alert-danger text-center py-2 my-1">Please enter some text</div>
        <div class="controls p-2 row mx-0 w-100">
            <input type="text" class="form-control col-sm-12 col-md-8" id="edit-tags" placeholder="Comma separated labels">
            <div class="div row mx-0 col-md-4 px-0">
                <select name="color" id="edit-color" class="custom-select col-6">
                    <option>White</option>
                    <option>Red</option>
                    <option>Green</option>
                    <option>Blue</option>
                    <option>Purple</option>
                </select>
                <button class="save-btn btn btn-light btn-outline-dark border font-weight-bold px-4 py-1 col-6" id="edit-note" type="submit">Save</button>
            </div>
        </div>
    </div>
{% endblock %}

note/templates/note/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Note{% endblock %}</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'note/styles/style.css' %}">
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-light bg-light mb-2" id="main-navbar">
    <div class="container">
        <a href="{% url 'note:index' %}" class="navbar-brand">Note</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="main-nav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <button id="index" class="nav-link btn">Notes</button>
                    </li>
                    <li class="nav-item">
                        <button id="archived-notes" class="nav-link btn">Archived</button>
                    </li>
                    <li class="nav-item">
                        <button id="labels-notes" class="nav-link btn">Labels</button>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'note:logout' %}" class="nav-link">Logout</a>
                    </li>
                {% endif %}
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'note:login' %}" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'note:register' %}" class="nav-link">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    </nav>


    <main class="container">
        {% block main %}
        {% endblock %}
    </main>

    <script src="{% static 'note/scripts/main.js' %}" type="module"></script>

    <!-- Third party scripts-->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
</body>
</html>

note/templates/note/login.html
{% extends 'note/layout.html' %}

{% block title %}
    Note | Login
{% endblock %}

{% block main %}
    <h1 class="display-4 text-center">Login</h1>

    <form action="{% url 'note:login' %}" method="post" id="login-form" novalidate>
        {% csrf_token %}
        {% if message %}
          <div class="alert alert-warning text-center">{{message}}</div>
        {% endif %}
        <div class="form-group">
            <label for="id_username">Username</label>
            <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required>
            <div class="invalid-feedback">Please enter username.</div>
        </div>
        <div class="form-group">
            <label for="id_password">Password</label>
            <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
            <div class="invalid-feedback">Please enter password</div>
        </div>
        <input type="submit" value="Login" class="btn btn-primary d-block mx-auto">
    </form>

    <div class="alert text-center">
        Don't have an account? <a class="text-primary" href="{% url 'note:register' %}">Register Here.</a>
    </div>

    <script>
        'use strict';
        // get the login form
        const loginForm = document.querySelector("#login-form");
        loginForm.addEventListener('submit', (e) => {
            // check form validity
            if (loginForm.checkValidity() === false) {
                e.preventDefault();
                loginForm.classList.add('was-validated');
            }
        });
    </script>
{% endblock %}

note/templates/note/register.html
{% extends 'note/layout.html' %}

{% block title %}
    Note | Register
{% endblock %}

{% block main %}
    <h1 class="display-4 text-center">Register</h1>

    {% include 'note/utils/form_error.html' with errors=register_form.non_fields_errors %}
    <form action="{% url 'note:register' %}" method="post" id="register-form" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username</label>
            {% include 'note/utils/form_error.html' with errors=register_form.username.errors %}
            <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" value="{{register_form.username.value}}" required>
            <div class="invalid-feedback">Please enter username.</div>
        </div>
        <div class="form-group">
            <label for="id_email">Email</label>
            {% include 'note/utils/form_error.html' with errors=register_form.email.errors %}
            <input type="email" name="email" id="id_email" class="form-control" placeholder="Email" value="{{register_form.email.value}}" required>
            <div class="invalid-feedback">Please enter email.</div>
        </div>

        <div class="form-group">
            <label for="id_password">Password</label>
            {% include 'note/utils/form_error.html' with errors=register_form.password.errors %}
            <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
            <div class="invalid-feedback">Please enter password.</div>
        </div>
        <div class="form-group">
            <label for="id_password_confirmation">Confirm Password</label>
            {% include 'note/utils/form_error.html' with errors=register_form.password_confirmation.errors %}
            <input type="password" name="password_confirmation" id="id_password_confirmation" class="form-control" placeholder="Retype Password" required>
            <div class="invalid-feedback">Please confirm your password.</div>
        </div>
        <input type="submit" value="Register" class="btn btn-primary d-block mx-auto">
    </form>

    <div class="alert text-center">
        Already have an account? <a class="text-success" href="{% url 'note:login' %}">Login Here.</a>
    </div>

    <script>
        'use strict';

        const registerForm = document.querySelector('#register-form');
        registerForm.addEventListener('submit', (e) => {
            if (registerForm.checkValidity() === false) {
                e.preventDefault();
                registerForm.classList.add('was-validated');
            }
        });
    </script>
{% endblock %}